# Generated by Django 4.2.15 on 2025-04-15 16:23

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("standup", "0001_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="quote",
            name="last_viewed",
            field=models.DateTimeField(blank=True, null=True),
        ),
    ]
