# Generated by Django 4.2.20 on 2025-04-29 13:50

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standup', '0002_quote_last_viewed'),
    ]

    operations = [
        migrations.CreateModel(
            name='DailyUserStandup',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField(unique=True)),
                ('slack_thread_ts', models.CharField(blank=True, max_length=20, null=True)),
                ('conductor', models.ForeignKey(blank=True, help_text='User responsible for conducting the stand-up', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('fallback_conductor', models.ForeignKey(blank=True, help_text='Fallback user when conductor is not available', null=True, on_delete=django.db.models.deletion.SET_NULL, related_name='+', to=settings.AUTH_USER_MODEL)),
                ('quote', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standup.quote')),
            ],
        ),
    ]
