# Generated by Django 4.2.20 on 2025-05-05 15:01

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('standup', '0003_dailyuserstandup'),
    ]

    operations = [
        migrations.CreateModel(
            name='StandupGatherAroundMedia',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('created_at', models.DateTimeField(auto_now_add=True)),
                ('modified_at', models.DateTimeField(auto_now=True)),
                ('url', models.URLField(help_text='Gif/Image to show during standup reminder')),
                ('caption', models.CharField(help_text='A short piece of text that describes the media')),
                ('last_viewed', models.DateTimeField(blank=True, null=True)),
                ('created_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_created', to=settings.AUTH_USER_MODEL)),
                ('modified_by', models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, related_name='%(class)s_modified', to=settings.AUTH_USER_MODEL)),
            ],
            options={
                'ordering': ['-id'],
                "verbose_name_plural": "standup gather around media",
                'abstract': False,
            },
        ),
        migrations.AddField(
            model_name='dailyuserstandup',
            name='gather_around_media',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='standup.standupgatheraroundmedia'),
        ),
    ]
