# Generated by Django 4.2.20 on 2025-05-05 15:44

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('standup', '0004_standupgatheraroundmedia_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='quote',
            name='auto_select',
            field=models.BooleanField(default=True, help_text='Exclude from automatic selection. If false, it must be manually assigned to the DailyUserStandup.'),
        ),
        migrations.AddField(
            model_name='standupgatheraroundmedia',
            name='auto_select',
            field=models.BooleanField(default=True, help_text='Exclude from automatic selection. If false, it must be manually assigned to the DailyUserStandup.'),
        ),
    ]
