type AppEnumCollection {
  EventType: [AppEnumCollectionEventType!]!
  UserDepartment: [AppEnumCollectionUserDepartment!]!
  TimeEntryType: [AppEnumCollectionTimeEntryType!]!
  TimeEntryStatus: [AppEnumCollectionTimeEntryStatus!]!
  JournalLeaveType: [AppEnumCollectionJournalLeaveType!]!
  JournalWfhType: [AppEnumCollectionJournalWfhType!]!
}

type AppEnumCollectionEventType {
  key: EventTypeEnum!
  label: String!
}

type AppEnumCollectionJournalLeaveType {
  key: JournalLeaveTypeEnum!
  label: String!
}

type AppEnumCollectionJournalWfhType {
  key: JournalWorkFromHomeTypeEnum!
  label: String!
}

type AppEnumCollectionTimeEntryStatus {
  key: TimeEntryStatusEnum!
  label: String!
}

type AppEnumCollectionTimeEntryType {
  key: TimeEntryTypeEnum!
  label: String!
}

type AppEnumCollectionUserDepartment {
  key: UserDepartmentTypeEnum!
  label: String!
}

input BoolBaseFilterLookup {
  """Exact match. Filter will be skipped on `null` value"""
  exact: Boolean

  """Assignment test. Filter will be skipped on `null` value"""
  isNull: Boolean

  """
  Exact match of items in a given list. Filter will be skipped on `null` value
  """
  inList: [Boolean!]
}

input ClientFilter {
  id: IDBaseFilterLookup
  name: StrFilterLookup
  AND: ClientFilter
  OR: ClientFilter
  NOT: ClientFilter
  DISTINCT: Boolean
}

interface ClientIdMixin {
  clientId: ID!
}

input ClientOrder {
  id: Ordering
  name: Ordering
}

type ClientType implements UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
  id: ID!
  name: String!
}

type ClientTypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [ClientType!]!
}

input ContractFilter {
  id: IDBaseFilterLookup
  projectId: IDBaseFilterLookup
  isArchived: BoolBaseFilterLookup
  AND: ContractFilter
  OR: ContractFilter
  NOT: ContractFilter
  DISTINCT: Boolean
}

input ContractOrder {
  id: Ordering
  name: Ordering
  createdAt: Ordering
}

type ContractType implements UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
  id: ID!
  projectId: ID!
  totalEstimatedHours: Float
  isArchived: Boolean!
  name: String!
  description: String
  project: ProjectType!

  """Sum of all task's estimated hours under this contract"""
  totalTasksEstimatedHours: Float!
}

type ContractTypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [ContractType!]!
}

input ContractorFilter {
  id: IDBaseFilterLookup
  name: StrFilterLookup
  AND: ContractorFilter
  OR: ContractorFilter
  NOT: ContractorFilter
  DISTINCT: Boolean
}

input ContractorOrder {
  id: Ordering
  name: Ordering
}

type ContractorType implements UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
  id: ID!
  name: String!
}

type ContractorTypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [ContractorType!]!
}

"""A generic type to return error messages"""
scalar CustomErrorType

type DailyStandUpProjectStatType {
  id: ID!
  lastWorkingDate: Date!
  activityFromDate: Date!
  project: ProjectType!
  users: [DailyStandUpProjectStatUserType!]!
}

type DailyStandUpProjectStatUserType {
  id: ID!
  lastActiveDate: Date!
  displayPicture: String @deprecated(reason: "Use user.display_picture instead")
  displayName: String! @deprecated(reason: "Use user.display_name instead")
  user: UserType!
  leave: JournalLeaveTypeEnum
  workFromHome: JournalWorkFromHomeTypeEnum
}

type DailyStandUpType {
  quote: QuoteType
  projectStat(pk: ID!): DailyStandUpProjectStatType
}

"""Date (isoformat)"""
scalar Date

input DateDateFilterLookup {
  """Exact match. Filter will be skipped on `null` value"""
  exact: Date

  """Assignment test. Filter will be skipped on `null` value"""
  isNull: Boolean

  """
  Exact match of items in a given list. Filter will be skipped on `null` value
  """
  inList: [Date!]

  """Greater than. Filter will be skipped on `null` value"""
  gt: Date

  """Greater than or equal to. Filter will be skipped on `null` value"""
  gte: Date

  """Less than. Filter will be skipped on `null` value"""
  lt: Date

  """Less than or equal to. Filter will be skipped on `null` value"""
  lte: Date

  """Inclusive range test (between)"""
  range: DateRangeLookup
  year: IntComparisonFilterLookup
  month: IntComparisonFilterLookup
  day: IntComparisonFilterLookup
  weekDay: IntComparisonFilterLookup
  isoWeekDay: IntComparisonFilterLookup
  week: IntComparisonFilterLookup
  isoYear: IntComparisonFilterLookup
  quarter: IntComparisonFilterLookup
}

input DateRangeLookup {
  start: Date = null
  end: Date = null
}

"""Date with time (isoformat)"""
scalar DateTime

type DeadlineType implements UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
  id: ID!
  startDate: Date!
  endDate: Date!
  isExternal: Boolean!
  projectId: ID!
  contractId: ID
  name: String!
  displayName: String!
  totalDays: Int!
  usedDays: Int!
  remainingDays: Int! @deprecated(reason: "Use total_days - used_days instead")
}

type DjangoImageType {
  name: String!
  size: Int!
  url: String!
  width: Int!
  height: Int!
}

input DjangoModelFilterInput {
  pk: ID!
}

input EventFilter {
  id: IDBaseFilterLookup
  startDate: DateDateFilterLookup
  endDate: DateDateFilterLookup
  types: [EventTypeEnum!]!
  AND: EventFilter
  OR: EventFilter
  NOT: EventFilter
  DISTINCT: Boolean
}

input EventOrder {
  id: Ordering
  name: Ordering
  startDate: Ordering
  endDate: Ordering
}

type EventType implements UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
  id: ID!
  startDate: Date!
  endDate: Date!
  name: String!
  type: EventTypeEnum!
  typeDisplay: String!
  dates: [Date!]!
  isActive: Boolean!
  remainingDaysToStart: Int!
  remainingDaysToEnd: Int!
}

type EventTypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [EventType!]!
}

enum EventTypeEnum {
  HOLIDAY
  RETREAT
  MISC
}

input IDBaseFilterLookup {
  """Exact match. Filter will be skipped on `null` value"""
  exact: ID

  """Assignment test. Filter will be skipped on `null` value"""
  isNull: Boolean

  """
  Exact match of items in a given list. Filter will be skipped on `null` value
  """
  inList: [ID!]
}

input IntComparisonFilterLookup {
  """Exact match. Filter will be skipped on `null` value"""
  exact: Int

  """Assignment test. Filter will be skipped on `null` value"""
  isNull: Boolean

  """
  Exact match of items in a given list. Filter will be skipped on `null` value
  """
  inList: [Int!]

  """Greater than. Filter will be skipped on `null` value"""
  gt: Int

  """Greater than or equal to. Filter will be skipped on `null` value"""
  gte: Int

  """Less than. Filter will be skipped on `null` value"""
  lt: Int

  """Less than or equal to. Filter will be skipped on `null` value"""
  lte: Int

  """Inclusive range test (between)"""
  range: IntRangeLookup
}

input IntRangeLookup {
  start: Int = null
  end: Int = null
}

enum JournalLeaveTypeEnum {
  FULL
  FIRST_HALF
  SECOND_HALF
}

type JournalType {
  id: ID!
  userId: ID!
  date: Date!
  leaveType: JournalLeaveTypeEnum
  leaveTypeDisplay: String
  wfhType: JournalWorkFromHomeTypeEnum
  wfhTypeDisplay: String
  journalText: String
  user: UserType!
}

type JournalTypeMutationResponseType {
  ok: Boolean!
  errors: CustomErrorType
  result: JournalType
}

input JournalUpdateInput {
  leaveType: JournalLeaveTypeEnum
  wfhType: JournalWorkFromHomeTypeEnum
  journalText: String
}

enum JournalWorkFromHomeTypeEnum {
  FULL
  FIRST_HALF
  SECOND_HALF
}

input LoginInput {
  email: String!
  password: String!
}

type Mutation {
  public: PublicMutation!
  private: PrivateMutation!
}

type MutationEmptyResponseType {
  ok: Boolean!
  errors: CustomErrorType
}

input OffsetPaginationInput {
  offset: Int! = 0
  limit: Int! = -1
}

enum Ordering {
  ASC
  ASC_NULLS_FIRST
  ASC_NULLS_LAST
  DESC
  DESC_NULLS_FIRST
  DESC_NULLS_LAST
}

type PrivateMutation {
  createTimeEntry(data: TimeEntryCreateInput!): TimeEntryTypeMutationResponseType!
  updateTimeEntry(id: ID!, data: TimeEntryUpdateInput!): TimeEntryTypeMutationResponseType!
  bulkTimeEntry(items: [TimeEntryBulkCreateInput!] = [], deleteIds: [ID!] = []): TimeEntryTypeBulkMutationResponseType!
  updateJournal(date: Date!, data: JournalUpdateInput!): JournalTypeMutationResponseType!
  id: ID!
}

type PrivateQuery {
  users(filters: UserFilter, order: UserOrder, pagination: OffsetPaginationInput): UserTypeCountList!
  dailyStandup(date: Date!): DailyStandUpType!
  clients(filters: ClientFilter, order: ClientOrder, pagination: OffsetPaginationInput): ClientTypeCountList!
  contractors(filters: ContractorFilter, order: ContractorOrder, pagination: OffsetPaginationInput): ContractorTypeCountList!
  projects(filters: ProjectFilter, order: ProjectOrder, pagination: OffsetPaginationInput): ProjectTypeCountList!
  allProjects: [ProjectType!]!
  allDeadlines: [DeadlineType!]!
  client(pk: ID!): ClientType
  contractor(pk: ID!): ContractorType
  project(pk: ID!): ProjectType
  contracts(filters: ContractFilter, order: ContractOrder, pagination: OffsetPaginationInput): ContractTypeCountList!
  tasks(filters: TaskFilter, order: TaskOrder, pagination: OffsetPaginationInput): TaskTypeCountList!
  timeEntries(filters: TimeEntryFilter, order: TimeEntryOrder, pagination: OffsetPaginationInput): TimeEntryTypeCountList!

  """Return all UnArchived contracts"""
  allActiveContracts: [ContractType!]!

  """Return all UnArchived tasks"""
  allActiveTasks: [TaskType!]!
  myTimeEntries(date: Date!): [TimeEntryType!]!
  allTimeEntries(filters: TimeEntryFilter!): [TimeEntryType!]!
  contract(pk: ID!): ContractType
  task(pk: ID!): TaskType
  journal(date: Date!): JournalType
  events(filters: EventFilter, order: EventOrder, pagination: OffsetPaginationInput): EventTypeCountList!
  relativeEvents: [EventType!]!
  id: ID!
}

input ProjectFilter {
  id: IDBaseFilterLookup
  projectClient: DjangoModelFilterInput
  contractor: DjangoModelFilterInput
  AND: ProjectFilter
  OR: ProjectFilter
  NOT: ProjectFilter
  DISTINCT: Boolean
}

input ProjectOrder {
  id: Ordering
  name: Ordering
}

type ProjectType implements UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
  id: ID!
  logo: DjangoImageType
  logoHd: DjangoImageType
  slideOrder: Int!
  projectClientId: ID!
  contractorId: ID!
  name: String!
  description: String
  projectClient: ClientType!
  contractor: ContractorType!
  deadlines: [DeadlineType!]!
}

type ProjectTypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [ProjectType!]!
}

type PublicMutation {
  login(data: LoginInput!): UserMeTypeMutationResponseType!
  logout: MutationEmptyResponseType!
  id: ID!
}

type PublicQuery {
  me: UserMeType
  id: ID!
}

type Query {
  public: PublicQuery!
  private: PrivateQuery!
  enums: AppEnumCollection!
}

type QuoteType implements UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
  id: ID!
  text: String!
  author: String!
}

input StrFilterLookup {
  """Exact match. Filter will be skipped on `null` value"""
  exact: String

  """Assignment test. Filter will be skipped on `null` value"""
  isNull: Boolean

  """
  Exact match of items in a given list. Filter will be skipped on `null` value
  """
  inList: [String!]

  """Case-insensitive exact match. Filter will be skipped on `null` value"""
  iExact: String

  """
  Case-sensitive containment test. Filter will be skipped on `null` value
  """
  contains: String

  """
  Case-insensitive containment test. Filter will be skipped on `null` value
  """
  iContains: String

  """Case-sensitive starts-with. Filter will be skipped on `null` value"""
  startsWith: String

  """Case-insensitive starts-with. Filter will be skipped on `null` value"""
  iStartsWith: String

  """Case-sensitive ends-with. Filter will be skipped on `null` value"""
  endsWith: String

  """Case-insensitive ends-with. Filter will be skipped on `null` value"""
  iEndsWith: String

  """
  Case-sensitive regular expression match. Filter will be skipped on `null` value
  """
  regex: String

  """
  Case-insensitive regular expression match. Filter will be skipped on `null` value
  """
  iRegex: String
}

input TaskFilter {
  id: IDBaseFilterLookup
  contractId: IDBaseFilterLookup
  isArchived: BoolBaseFilterLookup
  AND: TaskFilter
  OR: TaskFilter
  NOT: TaskFilter
  DISTINCT: Boolean
  project: ID
}

input TaskOrder {
  id: Ordering
  name: Ordering
  createdAt: Ordering
}

type TaskType implements UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
  id: ID!
  estimatedHours: Float
  isArchived: Boolean!
  contractId: ID!
  name: String!
  contract: ContractType!
}

type TaskTypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [TaskType!]!
}

"""Time (isoformat)"""
scalar Time

"""The `TimeDuration` scalar type represents Duration values in minutes"""
scalar TimeDuration

input TimeEntryBulkCreateInput {
  task: ID!
  date: Date!
  status: TimeEntryStatusEnum!
  id: ID
  type: TimeEntryTypeEnum
  description: String
  duration: TimeDuration
  startTime: Time
  clientId: ID
}

input TimeEntryCreateInput {
  task: ID!
  date: Date!
  status: TimeEntryStatusEnum!
  type: TimeEntryTypeEnum
  description: String
  duration: TimeDuration
  startTime: Time
  clientId: ID
}

enum TimeEntryDateFilterEnum {
  LAST_WORKING_DAY
  TODAY
}

input TimeEntryFilter {
  id: IDBaseFilterLookup
  task: DjangoModelFilterInput
  date: DateDateFilterLookup
  AND: TimeEntryFilter
  OR: TimeEntryFilter
  NOT: TimeEntryFilter
  DISTINCT: Boolean
  dateGte: TimeEntryDateFilterEnum
  dateLte: TimeEntryDateFilterEnum
  users: [ID!]
  types: [TimeEntryTypeEnum!]
  statuses: [TimeEntryStatusEnum!]
  project: ID
  contract: ID
}

input TimeEntryOrder {
  id: Ordering
  date: Ordering
}

enum TimeEntryStatusEnum {
  DOING
  DONE
  TODO
}

type TimeEntryType implements ClientIdMixin {
  clientId: ID!
  id: ID!
  date: Date!
  userId: ID!
  taskId: ID!
  startTime: Time
  createdAt: DateTime!
  duration: TimeDuration
  status: TimeEntryStatusEnum!
  statusDisplay: String!
  type: TimeEntryTypeEnum
  typeDisplay: String
  description: String
  user: UserType!
  task: TaskType!
}

type TimeEntryTypeBulkMutationResponseType {
  errors: [CustomErrorType!]
  results: [TimeEntryType!]
  deleted: [TimeEntryType!]
}

type TimeEntryTypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [TimeEntryType!]!
}

enum TimeEntryTypeEnum {
  DOCUMENTATION
  RESEARCH
  DESIGN
  OPERATION
  PROJECT_MANAGEMENT
  TESTING
  DEVELOPMENT
  DEV_OPS
  EXTERNAL_DISCUSSION
  INTERNAL_DISCUSSION
  EXTERNAL_MEETING
  INTERNAL_MEETING
}

type TimeEntryTypeMutationResponseType {
  ok: Boolean!
  errors: CustomErrorType
  result: TimeEntryType
}

input TimeEntryUpdateInput {
  task: ID
  date: Date
  type: TimeEntryTypeEnum
  description: String
  status: TimeEntryStatusEnum
  duration: TimeDuration
  startTime: Time
  clientId: ID
}

interface UserBaseType {
  id: ID!
  firstName: String
  lastName: String
  displayName: String
  displayPicture: String
  department: UserDepartmentTypeEnum
  departmentDisplay: String
  leaveToday: JournalLeaveTypeEnum
  workFromHomeToday: JournalWorkFromHomeTypeEnum
}

enum UserDepartmentTypeEnum {
  DATA_ANALYST
  DESIGN
  DEVELOPMENT
  MANAGEMENT
  PROJECT_MANAGER
  QUALITY_ASSURANCE
}

input UserFilter {
  id: IDBaseFilterLookup
  displayName: StrFilterLookup
  AND: UserFilter
  OR: UserFilter
  NOT: UserFilter
  DISTINCT: Boolean
  departments: [UserDepartmentTypeEnum!]
}

type UserMeType implements UserBaseType {
  id: ID!
  firstName: String
  lastName: String
  displayName: String
  displayPicture: String
  department: UserDepartmentTypeEnum
  departmentDisplay: String
  leaveToday: JournalLeaveTypeEnum
  workFromHomeToday: JournalWorkFromHomeTypeEnum
  email: String!
  isStaff: Boolean!
  isSuperuser: Boolean!
  myLastWorkingDate: Date!
}

type UserMeTypeMutationResponseType {
  ok: Boolean!
  errors: CustomErrorType
  result: UserMeType
}

input UserOrder {
  id: Ordering
  displayName: Ordering
  department: Ordering
}

interface UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
}

type UserType implements UserBaseType {
  id: ID!
  firstName: String
  lastName: String
  displayName: String
  displayPicture: String
  department: UserDepartmentTypeEnum
  departmentDisplay: String
  leaveToday: JournalLeaveTypeEnum
  workFromHomeToday: JournalWorkFromHomeTypeEnum
}

type UserTypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [UserType!]!
}
