type AppEnumCollection {
  TimeEntryType: [AppEnumCollectionTimeEntryType!]!
  TimeEntryStatus: [AppEnumCollectionTimeEntryStatus!]!
  JournalLeaveType: [AppEnumCollectionJournalLeaveType!]!
}

type AppEnumCollectionJournalLeaveType {
  key: JournalLeaveTypeEnum!
  label: String!
}

type AppEnumCollectionTimeEntryStatus {
  key: TimeEntryStatusEnum!
  label: String!
}

type AppEnumCollectionTimeEntryType {
  key: TimeEntryTypeEnum!
  label: String!
}

input BoolBaseFilterLookup {
  """Exact match. Filter will be skipped on `null` value"""
  exact: Boolean

  """Assignment test. Filter will be skipped on `null` value"""
  isNull: Boolean

  """
  Exact match of items in a given list. Filter will be skipped on `null` value
  """
  inList: [Boolean!]
}

input ClientFilter {
  id: IDBaseFilterLookup
  name: StrFilterLookup
  AND: ClientFilter
  OR: ClientFilter
  NOT: ClientFilter
  DISTINCT: Boolean
}

interface ClientIdMixin {
  clientId: ID!
}

input ClientOrder {
  id: Ordering
  name: Ordering
}

type ClientType implements UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
  id: ID!
  name: String!
}

type ClientTypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [ClientType!]!
}

input ContractFilter {
  id: IDBaseFilterLookup
  projectId: IDBaseFilterLookup
  isArchived: BoolBaseFilterLookup
  AND: ContractFilter
  OR: ContractFilter
  NOT: ContractFilter
  DISTINCT: Boolean
}

input ContractOrder {
  id: Ordering
  name: Ordering
  createdAt: Ordering
}

type ContractType implements UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
  id: ID!
  projectId: ID!
  totalEstimatedHours: Float
  isArchived: Boolean!
  name: String!
  description: String
  project: ProjectType!

  """Sum of all task's estimated hours under this contract"""
  totalTasksEstimatedHours: Float!
}

type ContractTypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [ContractType!]!
}

input ContractorFilter {
  id: IDBaseFilterLookup
  name: StrFilterLookup
  AND: ContractorFilter
  OR: ContractorFilter
  NOT: ContractorFilter
  DISTINCT: Boolean
}

input ContractorOrder {
  id: Ordering
  name: Ordering
}

type ContractorType implements UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
  id: ID!
  name: String!
}

type ContractorTypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [ContractorType!]!
}

"""A generic type to return error messages"""
scalar CustomErrorType

"""Date (isoformat)"""
scalar Date

input DateDateFilterLookup {
  """Exact match. Filter will be skipped on `null` value"""
  exact: Date

  """Assignment test. Filter will be skipped on `null` value"""
  isNull: Boolean

  """
  Exact match of items in a given list. Filter will be skipped on `null` value
  """
  inList: [Date!]

  """Greater than. Filter will be skipped on `null` value"""
  gt: Date

  """Greater than or equal to. Filter will be skipped on `null` value"""
  gte: Date

  """Less than. Filter will be skipped on `null` value"""
  lt: Date

  """Less than or equal to. Filter will be skipped on `null` value"""
  lte: Date

  """Inclusive range test (between)"""
  range: DateRangeLookup
  year: IntComparisonFilterLookup
  month: IntComparisonFilterLookup
  day: IntComparisonFilterLookup
  weekDay: IntComparisonFilterLookup
  isoWeekDay: IntComparisonFilterLookup
  week: IntComparisonFilterLookup
  isoYear: IntComparisonFilterLookup
  quarter: IntComparisonFilterLookup
}

input DateRangeLookup {
  start: Date = null
  end: Date = null
}

"""Date with time (isoformat)"""
scalar DateTime

type DjangoImageType {
  name: String!
  path: String!
  size: Int!
  url: String!
  width: Int!
  height: Int!
}

input DjangoModelFilterInput {
  pk: ID!
}

input IDBaseFilterLookup {
  """Exact match. Filter will be skipped on `null` value"""
  exact: ID

  """Assignment test. Filter will be skipped on `null` value"""
  isNull: Boolean

  """
  Exact match of items in a given list. Filter will be skipped on `null` value
  """
  inList: [ID!]
}

input IntComparisonFilterLookup {
  """Exact match. Filter will be skipped on `null` value"""
  exact: Int

  """Assignment test. Filter will be skipped on `null` value"""
  isNull: Boolean

  """
  Exact match of items in a given list. Filter will be skipped on `null` value
  """
  inList: [Int!]

  """Greater than. Filter will be skipped on `null` value"""
  gt: Int

  """Greater than or equal to. Filter will be skipped on `null` value"""
  gte: Int

  """Less than. Filter will be skipped on `null` value"""
  lt: Int

  """Less than or equal to. Filter will be skipped on `null` value"""
  lte: Int

  """Inclusive range test (between)"""
  range: IntRangeLookup
}

input IntRangeLookup {
  start: Int = null
  end: Int = null
}

enum JournalLeaveTypeEnum {
  FULL
  FIRST_HALF
  SECOND_HALF
}

type JournalType {
  id: ID!
  userId: ID!
  date: Date!
  leaveType: JournalLeaveTypeEnum
  leaveTypeDisplay: String
  journalText: String
  user: UserType!
}

type JournalTypeMutationResponseType {
  ok: Boolean!
  errors: CustomErrorType
  result: JournalType
}

input JournalUpdateInput {
  leaveType: JournalLeaveTypeEnum
  journalText: String
}

input LoginInput {
  email: String!
  password: String!
}

type Mutation {
  public: PublicMutation!
  private: PrivateMutation!
}

type MutationEmptyResponseType {
  ok: Boolean!
  errors: CustomErrorType
}

input OffsetPaginationInput {
  offset: Int! = 0
  limit: Int! = -1
}

enum Ordering {
  ASC
  ASC_NULLS_FIRST
  ASC_NULLS_LAST
  DESC
  DESC_NULLS_FIRST
  DESC_NULLS_LAST
}

type PrivateMutation {
  createTimeEntry(data: TimeEntryCreateInput!): TimeEntryTypeMutationResponseType!
  updateTimeEntry(id: ID!, data: TimeEntryUpdateInput!): TimeEntryTypeMutationResponseType!
  bulkTimeEntry(items: [TimeEntryBulkCreateInput!] = [], deleteIds: [ID!] = []): TimeEntryTypeBulkMutationResponseType!
  updateJournal(date: Date!, data: JournalUpdateInput!): JournalTypeMutationResponseType!
  id: ID!
}

type PrivateQuery {
  clients(filters: ClientFilter, order: ClientOrder, pagination: OffsetPaginationInput): ClientTypeCountList!
  contractors(filters: ContractorFilter, order: ContractorOrder, pagination: OffsetPaginationInput): ContractorTypeCountList!
  projects(filters: ProjectFilter, order: ProjectOrder, pagination: OffsetPaginationInput): ProjectTypeCountList!
  client(pk: ID!): ClientType
  contractor(pk: ID!): ContractorType
  project(pk: ID!): ProjectType
  contracts(filters: ContractFilter, order: ContractOrder, pagination: OffsetPaginationInput): ContractTypeCountList!
  tasks(filters: TaskFilter, order: TaskOrder, pagination: OffsetPaginationInput): TaskTypeCountList!
  timeEntries(filters: TimeEntryFilter, order: TimeEntryOrder, pagination: OffsetPaginationInput): TimeEntryTypeCountList!

  """Return all UnArchived contracts"""
  allActiveContracts: [ContractType!]!

  """Return all UnArchived tasks"""
  allActiveTasks: [TaskType!]!
  myTimeEntries(date: Date!): [TimeEntryType!]!
  contract(pk: ID!): ContractType
  task(pk: ID!): TaskType
  journal(date: Date!): JournalType
  id: ID!
}

input ProjectFilter {
  id: IDBaseFilterLookup
  projectClient: DjangoModelFilterInput
  contractor: DjangoModelFilterInput
  AND: ProjectFilter
  OR: ProjectFilter
  NOT: ProjectFilter
  DISTINCT: Boolean
}

input ProjectOrder {
  id: Ordering
  name: Ordering
}

type ProjectType implements UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
  id: ID!
  logo: DjangoImageType
  projectClientId: ID!
  contractorId: ID!
  name: String!
  description: String
  projectClient: ClientType!
  contractor: ContractorType!
}

type ProjectTypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [ProjectType!]!
}

type PublicMutation {
  login(data: LoginInput!): UserMeTypeMutationResponseType!
  logout: MutationEmptyResponseType!
  id: ID!
}

type PublicQuery {
  me: UserMeType
  id: ID!
}

type Query {
  public: PublicQuery!
  private: PrivateQuery!
  enums: AppEnumCollection!
}

input StrFilterLookup {
  """Exact match. Filter will be skipped on `null` value"""
  exact: String

  """Assignment test. Filter will be skipped on `null` value"""
  isNull: Boolean

  """
  Exact match of items in a given list. Filter will be skipped on `null` value
  """
  inList: [String!]

  """Case-insensitive exact match. Filter will be skipped on `null` value"""
  iExact: String

  """
  Case-sensitive containment test. Filter will be skipped on `null` value
  """
  contains: String

  """
  Case-insensitive containment test. Filter will be skipped on `null` value
  """
  iContains: String

  """Case-sensitive starts-with. Filter will be skipped on `null` value"""
  startsWith: String

  """Case-insensitive starts-with. Filter will be skipped on `null` value"""
  iStartsWith: String

  """Case-sensitive ends-with. Filter will be skipped on `null` value"""
  endsWith: String

  """Case-insensitive ends-with. Filter will be skipped on `null` value"""
  iEndsWith: String

  """
  Case-sensitive regular expression match. Filter will be skipped on `null` value
  """
  regex: String

  """
  Case-insensitive regular expression match. Filter will be skipped on `null` value
  """
  iRegex: String
}

input TaskFilter {
  id: IDBaseFilterLookup
  contractId: IDBaseFilterLookup
  isArchived: BoolBaseFilterLookup
  AND: TaskFilter
  OR: TaskFilter
  NOT: TaskFilter
  DISTINCT: Boolean
  project: ID
}

input TaskOrder {
  id: Ordering
  name: Ordering
  createdAt: Ordering
}

type TaskType implements UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
  id: ID!
  estimatedHours: Float
  isArchived: Boolean!
  contractId: ID!
  name: String!
  contract: ContractType!
}

type TaskTypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [TaskType!]!
}

"""Time (isoformat)"""
scalar Time

"""The `TimeDuration` scalar type represents Duration values in minutes"""
scalar TimeDuration

input TimeEntryBulkCreateInput {
  task: ID!
  date: Date!
  type: TimeEntryTypeEnum!
  status: TimeEntryStatusEnum!
  id: ID
  description: String
  duration: TimeDuration
  startTime: Time
  clientId: ID
}

input TimeEntryCreateInput {
  task: ID!
  date: Date!
  type: TimeEntryTypeEnum!
  status: TimeEntryStatusEnum!
  description: String
  duration: TimeDuration
  startTime: Time
  clientId: ID
}

input TimeEntryFilter {
  id: IDBaseFilterLookup
  user: DjangoModelFilterInput
  task: DjangoModelFilterInput
  date: DateDateFilterLookup
  types: [TimeEntryTypeEnum!]!
  AND: TimeEntryFilter
  OR: TimeEntryFilter
  NOT: TimeEntryFilter
  DISTINCT: Boolean
  project: ID
  contract: ID
}

input TimeEntryOrder {
  id: Ordering
  date: Ordering
}

enum TimeEntryStatusEnum {
  DOING
  DONE
  TODO
}

type TimeEntryType implements ClientIdMixin {
  clientId: ID!
  id: ID!
  date: Date!
  userId: ID!
  taskId: ID!
  startTime: Time
  createdAt: DateTime!
  duration: TimeDuration
  status: TimeEntryStatusEnum!
  statusDisplay: String!
  type: TimeEntryTypeEnum!
  typeDisplay: String!
  description: String
  user: UserType!
  task: TaskType!
}

type TimeEntryTypeBulkMutationResponseType {
  errors: [CustomErrorType!]
  results: [TimeEntryType!]
  deleted: [TimeEntryType!]
}

type TimeEntryTypeCountList {
  limit: Int!
  offset: Int!
  count: Int!
  items: [TimeEntryType!]!
}

enum TimeEntryTypeEnum {
  DESIGN
  DEVELOPMENT
  DEV_OPS
  DOCUMENTATION
  INTERNAL_DISCUSSION
  MEETING
  PROJECT_MANAGEMENT
  QUALITY_ASSURANCE
}

type TimeEntryTypeMutationResponseType {
  ok: Boolean!
  errors: CustomErrorType
  result: TimeEntryType
}

input TimeEntryUpdateInput {
  task: ID
  date: Date
  type: TimeEntryTypeEnum
  description: String
  status: TimeEntryStatusEnum
  duration: TimeDuration
  startTime: Time
  clientId: ID
}

type UserMeType {
  id: ID!
  firstName: String!
  lastName: String!
  displayName: String!
  displayPicture: String
  email: String!
}

type UserMeTypeMutationResponseType {
  ok: Boolean!
  errors: CustomErrorType
  result: UserMeType
}

interface UserResourceTypeMixin {
  createdAt: DateTime!
  modifiedAt: DateTime!
  createdBy: UserType!
  modifiedBy: UserType!
}

type UserType {
  id: ID!
  firstName: String!
  lastName: String!
  displayName: String!
}