# Generated by Django 4.2.14 on 2024-08-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0003_alter_user_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="display_picture",
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AlterField(
            model_name="user",
            name="department",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1000, "Data Analyst"),
                    (1100, "Design"),
                    (1200, "Development"),
                    (2000, "Management"),
                    (3000, "Project Manager"),
                    (5000, "QA"),
                ],
                null=True,
            ),
        ),
    ]
