# Generated by Django 4.2.15 on 2024-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("user", "0004_user_display_picture_alter_user_department"),
    ]

    operations = [
        migrations.AddField(
            model_name="user",
            name="exclude_from_slides",
            field=models.BooleanField(default=False),
        ),
        migrations.AlterField(
            model_name="user",
            name="display_name",
            field=models.CharField(blank=True, max_length=255),
        ),
    ]
