# Generated by Django 4.2.20 on 2025-04-29 13:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user', '0005_user_exclude_from_slides_alter_user_display_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='assign_for_standup',
            field=models.BooleanField(default=True),
        ),
        migrations.AddField(
            model_name='user',
            name='slack_user_id',
            field=models.CharField(blank=True, max_length=20, null=True),
        ),
    ]
