# Generated by Django 4.2.14 on 2024-08-04 04:54

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0003_contract_total_estimated_hours_task_estimated_hours_and_more"),
    ]

    operations = [
        migrations.AddField(
            model_name="timetrack",
            name="start_time",
            field=models.TimeField(blank=True, null=True),
        ),
    ]
