# Generated by Django 4.2.14 on 2024-08-05 11:44

from django.conf import settings
from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ("track", "0004_timetrack_start_time"),
    ]

    operations = [
        migrations.RenameModel(
            old_name="TimeTrack",
            new_name="TimeEntry",
        ),
    ]
