# Generated by Django 4.2.14 on 2024-08-05 11:52

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0005_rename_timetrack_timeentry"),
    ]

    operations = [
        migrations.RenameField(
            model_name="timeentry",
            old_name="task_type",
            new_name="type",
        ),
    ]
