# Generated by Django 4.2.14 on 2024-08-06 12:50

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0006_rename_task_type_timeentry_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeentry",
            name="is_done",
        ),
        migrations.AddField(
            model_name="timeentry",
            name="status",
            field=models.PositiveSmallIntegerField(choices=[(1, "Doing"), (2, "Done"), (3, "TODO")], default=2),
            preserve_default=False,
        ),
    ]
