# Generated by Django 4.2.14 on 2024-08-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0007_remove_timeentry_is_done_timeentry_status"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="timeentry",
            options={"verbose_name": "time entry", "verbose_name_plural": "time entries"},
        ),
    ]
