# Generated by Django 4.2.14 on 2024-08-07 16:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0008_alter_timeentry_options"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="client_id",
            field=models.CharField(blank=True, max_length=26, null=True),
        ),
    ]
