# Generated by Django 4.2.14 on 2024-08-08 11:04

import django.utils.timezone
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0009_timeentry_client_id"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="created_at",
            field=models.DateTimeField(auto_now_add=True, default=django.utils.timezone.now),
            preserve_default=False,
        ),
    ]
