# Generated by Django 4.2.15 on 2024-08-13 15:31

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0011_alter_timeentry_type"),
    ]

    operations = [
        migrations.RemoveField(
            model_name="timeentry",
            name="duration",
        ),
        # NOTE: At this state, we didn't have much data
        migrations.AddField(
            model_name="timeentry",
            name="duration",
            field=models.PositiveSmallIntegerField(blank=True, help_text="Minutes", null=True),
        ),
    ]
