# Generated by Django 4.2.15 on 2024-08-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0012_alter_timeentry_duration"),
    ]

    operations = [
        migrations.AddField(
            model_name="contract",
            name="description",
            field=models.TextField(blank=True),
        ),
    ]
