# Generated by Django 4.2.15 on 2024-08-22 11:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0013_contract_description"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="duration_adjustment",
            field=models.SmallIntegerField(
                blank=True,
                help_text="Minutes. Used to keep track of reported minutes. This will be used as duration (+- duration_adjustment)",
                null=True,
            ),
        ),
    ]
