# Generated by Django 4.2.15 on 2024-08-23 07:09

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0014_timeentry_duration_adjustment"),
    ]

    operations = [
        migrations.AddField(
            model_name="timeentry",
            name="is_billable",
            field=models.BooleanField(default=True),
        ),
    ]
