# Generated by Django 4.2.15 on 2024-08-23 07:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0015_timeentry_is_billable"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (1000, "Design"),
                    (1100, "Development"),
                    (1200, "DevOps"),
                    (2000, "Documentation"),
                    (3000, "Internal Discussion"),
                    (3100, "External Discussion"),
                    (4000, "Meeting"),
                    (5000, "Project Management"),
                    (6000, "QA"),
                ],
                null=True,
            ),
        ),
    ]
