# Generated by Django 4.2.15 on 2024-08-27 11:14

from django.db import migrations, models

TIME_ENTRY_TYPE_MIGRATION = {
    1000: 1,  # Design
    1200: 2,  # DevOps
    1100: 3,  # Development
    3100: 4,  # Discussion (External)
    3000: 5,  # Discussion (Internal)
    2000: 6,  # Documentation
    4000: 7,  # Meeting (External)
    5000: 10,  # Project Management
    6000: 12,  # Testing
}


def migrate_time_entry_data(apps, _):
    TimeEntry = apps.get_model("track", "TimeEntry")
    qs = TimeEntry.objects.all()

    print("Migrating data....")
    for existing_type_value, new_type_value in TIME_ENTRY_TYPE_MIGRATION.items():
        updated = qs.filter(type=existing_type_value).update(type=new_type_value)
        print(f"\t {existing_type_value} -> {new_type_value}: items updated: {updated}")


def revert_migrate_time_entry_data(apps, _):
    TimeEntry = apps.get_model("track", "TimeEntry")
    qs = TimeEntry.objects.all()

    print("Migrating back data....")
    for existing_type_value, new_type_value in TIME_ENTRY_TYPE_MIGRATION.items():
        updated = qs.filter(type=new_type_value).update(type=existing_type_value)
        print(f"\t {new_type_value} -> {existing_type_value}: items updated: {updated}")


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0016_alter_timeentry_type"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (6, "Documentation"),
                    (11, "Research"),
                    (1, "Design"),
                    (9, "Operation"),
                    (10, "Project Management"),
                    (12, "Testing"),
                    (3, "Development"),
                    (2, "DevOps"),
                    (4, "Discussion External"),
                    (5, "Discussion Internal"),
                    (7, "Meeting External"),
                    (8, "Meeting Internal"),
                ],
                null=True,
            ),
        ),
        migrations.RunPython(
            migrate_time_entry_data,
            reverse_code=revert_migrate_time_entry_data,
        ),
    ]
