# Generated by Django 4.2.15 on 2024-08-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0017_alter_timeentry_type"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="contract",
            options={},
        ),
        migrations.AlterModelOptions(
            name="task",
            options={},
        ),
        migrations.AddIndex(
            model_name="contract",
            index=models.Index(
                condition=models.Q(("is_archived", False)), fields=["is_archived"], name="track_contract_active_idx"
            ),
        ),
        migrations.AddIndex(
            model_name="task",
            index=models.Index(
                condition=models.Q(("is_archived", False)), fields=["is_archived"], name="track_task_active_idx"
            ),
        ),
    ]
