# Generated by Django 4.2.15 on 2024-09-06 01:57

from django.db import migrations

CREATE_SQL = """
CREATE OR REPLACE VIEW time_entry_analysis_query AS
  SELECT
    te.id,
    u.display_name as user_display_name,
    u.id as user_id,
    te.date,
    p.name as project_name,
    p.id as project_id,
    ct.name as contract_name,
    ct.id as contract_id,
    CASE
        WHEN te.type = 1 THEN 'Design'
        WHEN te.type = 2 THEN 'DevOps'
        WHEN te.type = 3 THEN 'Development'
        WHEN te.type = 6 THEN 'Documentation'
        WHEN te.type = 4 THEN 'Discussion - External'
        WHEN te.type = 7 THEN 'Meeting - External'
        WHEN te.type = 5 THEN 'Discussion - Internal'
        WHEN te.type = 8 THEN 'Meeting - Internal'
        WHEN te.type = 9 THEN 'Operation'
        WHEN te.type = 10 THEN 'Project Management'
        WHEN te.type = 11 THEN 'Research'
        WHEN te.type = 12 THEN 'Testing'
       ELSE te.type::text
    END as type_display,
    te.description,
    t.name as task_name,
    t.id as task_id,
    te.duration,
    te.duration_adjustment,
    te.is_billable,
    CASE
        WHEN te.is_billable THEN
          CAST((te.duration + COALESCE(te.duration_adjustment, 0)) as float) / 60
        ELSE 0
    END as hours,
    CAST(te.duration as float) / 60 as real_hours,
    CASE
       WHEN te.status = 1 THEN 'Doing'
       WHEN te.status = 2 THEN 'Done'
       WHEN te.status = 3 THEN 'Todo'
       ELSE 'N/A'
    END as status_display
  FROM track_timeentry te
  LEFT JOIN user_user u ON te.user_id = u.id
  LEFT JOIN track_task t ON te.task_id = t.id
  LEFT JOIN track_contract ct ON t.contract_id = ct.id
  LEFT JOIN project_project p ON ct.project_id = p.id;
"""

DROP_SQL = "DROP VIEW IF EXISTS time_entry_analysis_query;"


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0018_alter_contract_options_alter_task_options_and_more"),
    ]

    operations = [
        migrations.RunSQL(
            sql=CREATE_SQL,
            reverse_sql=DROP_SQL,
        ),
    ]
