# Generated by Django 4.2.15 on 2025-04-15 15:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("track", "0019_time_entry_sql_analysis_view"),
    ]

    operations = [
        migrations.AlterField(
            model_name="timeentry",
            name="type",
            field=models.PositiveSmallIntegerField(
                blank=True,
                choices=[
                    (6, "Documentation"),
                    (11, "Research"),
                    (1, "Design"),
                    (9, "Operations"),
                    (10, "Project Management"),
                    (12, "Testing"),
                    (3, "Development"),
                    (2, "DevOps"),
                    (4, "Discussion External"),
                    (5, "Discussion Internal"),
                    (7, "Meeting External"),
                    (8, "Meeting Internal"),
                ],
                null=True,
            ),
        ),
    ]
