# Generated by Django 4.2.20 on 2026-01-19 08:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0020_alter_timeentry_type'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='client_id',
            field=models.CharField(max_length=26),
        ),
    ]
