# Generated by Django 4.2.20 on 2026-05-03 08:00

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('track', '0021_alter_timeentry_client_id'),
    ]

    operations = [
        migrations.AlterField(
            model_name='timeentry',
            name='type',
            field=models.PositiveSmallIntegerField(blank=True, choices=[(6, 'Documentation'), (11, 'Research'), (13, 'Review'), (1, 'Design'), (9, 'Operations'), (10, 'Project Management'), (12, 'Testing'), (3, 'Development'), (2, 'DevOps'), (4, 'Discussion External'), (5, 'Discussion Internal'), (7, 'Meeting External'), (8, 'Meeting Internal'), (14, 'Annotation')], null=True),
        ),
    ]
