# Generated by Django 4.2.13 on 2024-06-18 10:58

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Journal',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('date', models.DateField()),
                ('leave_type', models.PositiveSmallIntegerField(blank=True, choices=[(1, 'Full'), (2, 'First Half'), (3, 'Second Half')], null=True)),
                ('journal_text', models.TextField(blank=True)),
            ],
        ),
    ]
