# Generated by Django 4.2.13 on 2024-06-18 10:58

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('journal', '0001_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='journal',
            name='user',
            field=models.ForeignKey(on_delete=django.db.models.deletion.CASCADE, related_name='+', to=settings.AUTH_USER_MODEL),
        ),
        migrations.AddIndex(
            model_name='journal',
            index=models.Index(fields=['date'], name='journal_jou_date_eb308c_idx'),
        ),
        migrations.AlterUniqueTogether(
            name='journal',
            unique_together={('user', 'date')},
        ),
    ]
