# Generated by Django 4.2.15 on 2024-08-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("journal", "0002_initial"),
    ]

    operations = [
        migrations.AddField(
            model_name="journal",
            name="wfh_type",
            field=models.PositiveSmallIntegerField(
                blank=True, choices=[(1, "Full"), (2, "First Half"), (3, "Second Half")], null=True
            ),
        ),
    ]
