# Generated by Django 4.2.15 on 2024-08-22 17:47

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = []

    operations = [
        migrations.CreateModel(
            name="Event",
            fields=[
                ("id", models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name="ID")),
                ("name", models.CharField(max_length=225)),
                ("date", models.DateField()),
                ("type", models.PositiveSmallIntegerField(choices=[(1, "Holiday"), (2, "Retreat"), (3, "Misc")], default=1)),
            ],
        ),
    ]
