# Generated by Django 4.2.14 on 2024-08-07 05:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0002_initial"),
    ]

    operations = [
        migrations.RenameField(
            model_name="project",
            old_name="client",
            new_name="project_client",
        ),
    ]
