# Generated by Django 4.2.15 on 2024-08-15 15:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0003_rename_client_project_project_client"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="logo",
            field=models.ImageField(blank=True, max_length=255, null=True, upload_to="project/logo/"),
        ),
    ]
