# Generated by Django 4.2.15 on 2024-08-26 12:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0005_project_is_archived_deadline"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="slide_order",
            field=models.PositiveSmallIntegerField(default=0, help_text="Used to order projects in daily stand-up slides"),
        ),
    ]
