# Generated by Django 4.2.15 on 2024-08-26 12:32

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0006_project_slide_order"),
    ]

    operations = [
        migrations.AddField(
            model_name="project",
            name="logo_hd",
            field=models.ImageField(
                blank=True, help_text="Hight quality logo", max_length=255, null=True, upload_to="project/logo-hd/"
            ),
        ),
        migrations.AlterField(
            model_name="project",
            name="logo",
            field=models.ImageField(
                blank=True, help_text="Low quality logo.", max_length=255, null=True, upload_to="project/logo/"
            ),
        ),
    ]
