# Generated by Django 4.2.15 on 2024-08-28 17:10

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0007_project_logo_hd_alter_project_logo"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="project",
            options={},
        ),
        migrations.AddIndex(
            model_name="project",
            index=models.Index(
                condition=models.Q(("is_archived", False)), fields=["is_archived"], name="project_project_active_idx"
            ),
        ),
    ]
