# Generated by Django 4.2.15 on 2024-08-28 18:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0008_alter_project_options_and_more"),
    ]

    operations = [
        migrations.AlterModelOptions(
            name="deadline",
            options={},
        ),
        migrations.AddIndex(
            model_name="deadline",
            index=models.Index(
                condition=models.Q(("is_archived", False)), fields=["is_archived"], name="project_deadline_active_idx"
            ),
        ),
    ]
