# Generated by Django 4.2.15 on 2024-09-09 15:46

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ("project", "0009_alter_deadline_options_and_more"),
    ]

    operations = [
        migrations.AlterField(
            model_name="deadline",
            name="end_date",
            field=models.DateField(help_text="This will be the date on which we need to deliver the work."),
        ),
        migrations.AlterField(
            model_name="deadline",
            name="start_date",
            field=models.DateField(help_text="This will be the date from which we need to start working."),
        ),
    ]
