# Generated by Django 4.2.20 on 2025-04-18 16:27

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0010_alter_deadline_end_date_alter_deadline_start_date'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='google_calendar_event_id',
            field=models.CharField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deadline',
            name='google_calendar_html_link',
            field=models.URLField(blank=True, null=True),
        ),
        migrations.AddField(
            model_name='deadline',
            name='google_calendar_sync_status',
            field=models.PositiveSmallIntegerField(choices=[(1, 'Pending'), (2, 'Success'), (3, 'Failure')], default=1),
        ),
    ]
