# Generated by Django 4.2.20 on 2025-04-22 12:29

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0011_deadline_google_calendar_event_id_and_more'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='is_external',
            field=models.BooleanField(default=True, help_text='This is the deadline for clients'),
        ),
    ]
