# Generated by Django 4.2.20 on 2025-04-22 15:09

from django.db import migrations, models


def copy_name_to_short_name(apps, _):
    Project = apps.get_model("project", "Project")
    resp = Project.objects.update(
        short_name=models.Func(
            models.F('name'),
            function='LEFT',
            template="%(function)s(%(expressions)s, 10)",  # Truncate to 10 characters
        ),
    )
    print(resp)


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0012_deadline_is_external'),
    ]

    operations = [
        migrations.AddField(
            model_name='project',
            name='short_name',
            field=models.CharField(default='CHANGE_ME', max_length=10),
            preserve_default=False,
        ),
        migrations.RunPython(
            copy_name_to_short_name,
            reverse_code=migrations.RunPython.noop,
        ),
    ]
