# Generated by Django 4.2.20 on 2025-06-02 09:30

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('project', '0013_project_short_name'),
    ]

    operations = [
        migrations.AddField(
            model_name='deadline',
            name='description',
            field=models.TextField(blank=True),
        ),
    ]
