apiVersion: v2
name: timur-backend-helm
description: "Helm Chart to deploy the Timur Backend"
type: application
version: 0.2.2-SET-BY-CICD  # managed by release.sh
sources:
  - https://github.com/toggle-corp/timur-backend

dependencies:
  - name: banjo-helm
    alias: app
    version: 0.2.8
    repository: oci://ghcr.io/toggle-corp
