app:
  environment: Alpha
  # Global Image
  image:
    name: ghcr.io/toggle-corp/timur-backend-alpha
    tag: test.123

  ingress:
    enabled: true
    className: nginx
    host: timur-api.k8s.local.com

  redis:
    master:
      persistence:
        size: .5Gi
        storageClass: longhorn

  postgresql:
    enabled: true
    auth:
      postgresPassword: "my-strong-root-passowrd"
      username: "timur"
      password: "my-strong-user-passowrd"
      database: "timur"
    primary:
      persistence:
        storageClass: "longhorn"
        size: 1Gi

  minio:
    enabled: true
    global:
      defaultStorageClass: longhorn
    apiIngress:
      enabled: true
      ingressClassName: nginx
      hostname: timur-minio.k8s.local.com
    auth:
      rootUser: timur
      rootPassword: my-strong-user-password
    persistence:
      enabled: true
      size: 0.5Gi

  api:
    resources:
      requests:
        cpu: "0.1"
        memory: 0.5Gi

  env:
    AWS_S3_ENABLED: "true"
    # App Domain
    APP_DOMAIN: https://timur-api.k8s.local.com
    APP_FRONTEND_HOST: https://timur.k8s.local.com
    SESSION_COOKIE_DOMAIN: .k8s.local.com
    CSRF_COOKIE_DOMAIN: .k8s.local.com
    # Email
    EMAIL_FROM: "timur.dev.com"
    # Google SSO
    GOOGLE_OAUTH_ENABLED: "true"

  secrets:
    DJANGO_SECRET_KEY: "very-strong-django-secret-key"
    # Google calendar
    GOOGLE_CALENDAR_ID: my-calender-id@group.calendar.google.com
    GOOGLE_CREDENTIALS_B64_GZ: GOOGLE_CREDENTIALS_B64_GZ_KEY
    # Sentry
    SENTRY_DSN: https://test-123@sentry.local.com/27
    # Google SSO
    GOOGLE_OAUTH_CLIENT_ID: my-client-id.apps.googleusercontent.com
    GOOGLE_OAUTH_REDIRECT_URL: https://timur-api.k8s.local.com/o/google
