name: Python check

on:
  pull_request:

jobs:
  build:
    name: CI
    uses: toggle-corp/toggle-django-action/.github/workflows/django-docker-ci.yml@main
    with:
      compose_file: "gh-docker-compose.yml"
      chart_directory: "./helm"
