name: Helm

on:
  workflow_dispatch:
  push:
    branches:
      - develop
      - main
      - master
      - project/*
      - chore/*
    tags:
      - "**"

permissions:
  packages: write

jobs:
  publish:
    uses: toggle-corp/toggle-django-action/.github/workflows/helm-publish.yml@main
    with:
      compose_file: "gh-docker-compose.yml"
      chart_directory: "./helm"
    secrets: inherit
