name: Generate release

on:
  push:
    tags:
      - "v*.*.*"

jobs:
  generate-release:
    name: Generate release
    runs-on: ubuntu-22.04

    steps:
      - name: Checkout
        uses: actions/checkout@v4
        with:
          fetch-depth: 0

      - name: Set the release version
        id: release
        shell: bash
        run: |
          RELEASE_VERSION=${GITHUB_REF:11}

          IS_PRERELEASE=false
          if [[ "$OTHER_VAR" == *dev* ]]; then
              IS_PRERELEASE=true
          fi

          echo "release_version=${RELEASE_VERSION}" >> $GITHUB_OUTPUT
          echo "is_prerelease=${IS_PRERELEASE}" >> $GITHUB_OUTPUT
          echo "::notice::Release version: ${RELEASE_VERSION}"
          echo "::notice::Is prerelease: ${IS_PRERELEASE}"

      - name: Generate a changelog
        uses: orhun/git-cliff-action@main
        id: git-cliff
        with:
          config: cliff.toml
          args: -vv --latest --no-exec --github-repo ${{ github.repository }}

      - name: Show changelog in summary
        shell: bash
        run: |
          echo "${{ steps.git-cliff.outputs.content }}" >> $GITHUB_STEP_SUMMARY

      # TODO: Add additional content to the release body. like helm & docker image
      - name: Create Github Release
        uses: softprops/action-gh-release@v2
        if: github.ref_type == 'tag'
        with:
          token: ${{ secrets.GITHUB_TOKEN }}
          name: "v${{ steps.release.outputs.release_version }}"
          body: ${{ steps.git-cliff.outputs.content }}
          prerelease: ${{ steps.release.outputs.is_prerelease }}
